name: csean_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.2.0
  device_info_plus: ^3.2.1
  devicelocale: ^0.5.0
  dio: ^4.0.4
  dotted_border: ^2.0.0+1
  google_fonts: ^2.2.0
  file_picker: ^4.3.3
  flutter_bloc: ^7.3.1
  flutter_html: ^2.2.1
  fluttertoast: ^8.0.8
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: patch/1.0.5+2
  flutter_user_agentx: ^1.2.4
  freezed_annotation: ^0.15.0
  get_it: ^7.2.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  permission_handler: ^9.1.0
  shared_preferences: ^2.0.12
  sprintf: ^6.0.0
  responsive_builder: ^0.4.1
  responsive_grid: ^2.0.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.18
  version_tracker: ^2.1.1
  waterfall_flow: ^3.0.2
  webview_flutter: ^2.3.1
  youtube_player_flutter: ^8.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^8.5.0
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.15.0+1
  json_serializable: ^6.1.4
  mockito: ^5.1.0
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/auth/
    - assets/place-holder/
    - assets/db/
    - assets/items/files/


  fonts:
    - family: DejaVuSans
      fonts:
        - asset: assets/fonts/DejaVuSans.ttf
          weight: 200
        - asset: assets/fonts/DejaVuSans-Bold.ttf
          weight: 700

